<script lang="ts">
  import { refreshUsageHistory, usageState } from './usageStore.svelte.ts';
  import { usageProviderLabel } from './usageCurrent.ts';

  const numberFormat = new Intl.NumberFormat('en-US');
  function totalTokens(): number {
    const summary = usageState.summary;
    return summary ? summary.inputTokens + summary.outputTokens + summary.cacheReadTokens + summary.cacheWriteTokens + summary.reasoningTokens : 0;
  }
  function visibleTokens(input: number): string {
    if (input >= 1_000_000_000) return `${(input / 1_000_000_000).toFixed(1)}B`;
    if (input >= 1_000_000) return `${(input / 1_000_000).toFixed(1)}M`;
    if (input >= 1_000) return `${(input / 1_000).toFixed(1)}K`;
    return numberFormat.format(input);
  }
  function costLabel(value: number | null): string { return value == null ? 'Unavailable' : `$${(value / 1_000_000).toFixed(2)}`; }
  function cacheShare(): number { const summary = usageState.summary; if (!summary) return 0; const total = totalTokens(); return total === 0 ? 0 : Math.round(((summary.cacheReadTokens + summary.cacheWriteTokens) / total) * 100); }
  function intensity(row: { inputTokens: number; outputTokens: number }): number { const max = Math.max(...usageState.daily.map((item) => item.inputTokens + item.outputTokens), 1); return Math.min(4, Math.ceil(((row.inputTokens + row.outputTokens) / max) * 4)); }
  function formatDay(day: string): string { const parsed = new Date(`${day}T00:00:00Z`); return Number.isNaN(parsed.getTime()) ? day : parsed.toLocaleDateString([], { month: 'short', day: 'numeric', timeZone: 'UTC' }); }
  let providerCards = $derived(usageState.providerSummary);
</script>

<section class="workspace" data-testid="usage-workspace" aria-label="Stats and Usage">
  <header class="workspace-header"><div><p class="eyebrow">Stats &amp; Usage</p><h2>Provider activity</h2><p class="muted">Local transcripts are indexed incrementally; aggregates stay in SQLite.</p></div><button type="button" onclick={() => void refreshUsageHistory()} disabled={usageState.loading}>{usageState.loading ? 'Indexing…' : 'Refresh'}</button></header>
  {#if usageState.summary}
    <div class="top-tiles"><div><strong>{numberFormat.format(usageState.summary.sessionCount)}</strong><span>Agents spawned</span></div><div><strong>{usageState.summary.activeDays ? `${usageState.summary.activeDays}d` : '—'}</strong><span>Active days</span></div><div><strong>—</strong><span>PRs created · not indexed</span></div></div>
    <p class="tracking">Tracking local usage · {usageState.summary.eventCount.toLocaleString('en-US')} explicit events</p>
    <section class="analytics-card"><div class="section-heading"><div><h3>Usage Overview</h3><p class="muted">Updated from the local index</p></div><button type="button" aria-label="Refresh analytics" onclick={() => void refreshUsageHistory()}>↻</button></div><div class="metric-grid"><div><strong>{visibleTokens(totalTokens())}</strong><span>Total tokens</span></div><div><strong>{costLabel(usageState.summary.estimatedCostMicros)}</strong><span>Est. cost</span></div><div><strong>{usageState.summary.activeDays}</strong><span>Active days</span></div><div><strong>{cacheShare()}%</strong><span>Cache share</span></div></div><div class="charts"><section class="chart"><div class="chart-heading"><div><h3>Daily intensity</h3><p class="muted">Input and output token activity by indexed day.</p></div><span class="badge">{usageState.daily.length} days</span></div><div class="heatmap">{#each usageState.daily.slice().reverse() as row (`${row.day}:${row.provider}:${row.model}`)}<span class={`level-${intensity(row)}`} title={`${formatDay(row.day)} · ${visibleTokens(row.inputTokens + row.outputTokens)}`}></span>{/each}</div><div class="legend"><span>{usageState.daily.length ? formatDay(usageState.daily[usageState.daily.length - 1].day) : 'No data'}</span><span>Less</span><i class="level-1"></i><i class="level-2"></i><i class="level-3"></i><i class="level-4"></i><span>More</span><span>{usageState.daily[0] ? formatDay(usageState.daily[0].day) : ''}</span></div></section><section class="chart"><div class="chart-heading"><div><h3>Token mix</h3><p class="muted">Input, output, cache, and reasoning.</p></div><span class="badge">{visibleTokens(totalTokens())}</span></div><div class="mix-bar"><i class="input" style={`width:${totalTokens() ? (usageState.summary.inputTokens / totalTokens()) * 100 : 0}%`}></i><i class="output" style={`width:${totalTokens() ? (usageState.summary.outputTokens / totalTokens()) * 100 : 0}%`}></i><i class="cache" style={`width:${totalTokens() ? ((usageState.summary.cacheReadTokens + usageState.summary.cacheWriteTokens) / totalTokens()) * 100 : 0}%`}></i><i class="reasoning" style={`width:${totalTokens() ? (usageState.summary.reasoningTokens / totalTokens()) * 100 : 0}%`}></i></div><div class="mix-legend"><span><i class="dot input"></i>Input {visibleTokens(usageState.summary.inputTokens)}</span><span><i class="dot output"></i>Output {visibleTokens(usageState.summary.outputTokens)}</span><span><i class="dot cache"></i>Cache {visibleTokens(usageState.summary.cacheReadTokens + usageState.summary.cacheWriteTokens)}</span></div></section></div></section>
    <section class="providers"><div class="section-heading"><div><h3>Providers</h3><p class="muted">{providerCards.length} indexed provider{providerCards.length === 1 ? '' : 's'}</p></div><span class="badge">{usageState.summary.eventCount} events</span></div><div class="provider-grid">{#each providerCards as card (card.provider)}<article><div class="provider-heading"><h3>{usageProviderLabel(card.provider)}</h3><span>Indexed</span></div><p class="muted">{card.models.join(' · ')}</p><div class="provider-stats"><span>{visibleTokens(card.inputTokens + card.outputTokens)}<small>tokens</small></span><span>{card.sessionCount}<small>sessions</small></span><span>{card.eventCount}<small>events</small></span></div><div class="provider-bar"><i style={`width:${Math.min(100, ((card.inputTokens + card.outputTokens) / Math.max(...providerCards.map((item) => item.inputTokens + item.outputTokens), 1)) * 100)}%`}></i></div></article>{/each}{#if providerCards.length === 0}<p class="muted">No provider activity has been indexed yet.</p>{/if}</div></section>
  {:else}<p class="empty">{usageState.error ?? 'Refresh to index local usage history.'}</p>{/if}
</section>

<style>
  .workspace { display: grid; gap: 1rem; padding: 1rem; color: var(--color-text); background: var(--color-surface); } .workspace-header { display: flex; justify-content: space-between; align-items: start; gap: 1rem; } h2, h3, p { margin: 0; } h2 { font-size: 1.35rem; } h3 { font-size: 1rem; } .eyebrow { margin-bottom: 0.2rem; color: var(--color-text-2); text-transform: uppercase; letter-spacing: 0.09em; font-size: 0.68rem; } .muted, .empty, .tracking, small { color: var(--color-text-2); } button { border: 0; background: var(--color-elevated); color: var(--color-text); border-radius: 0.45rem; padding: 0.45rem 0.7rem; font: inherit; cursor: pointer; } button:hover:not(:disabled) { background: var(--color-hover); } button:focus-visible { outline: none; box-shadow: var(--focus-ring); } button:disabled { cursor: not-allowed; opacity: 0.55; }
  .top-tiles, .metric-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 0.65rem; } .metric-grid { grid-template-columns: repeat(4, minmax(0, 1fr)); } .top-tiles > div, .metric-grid > div { display: grid; gap: 0.2rem; padding: 0.85rem; border: 1px solid var(--color-border); border-radius: 0.55rem; background: var(--color-elevated); } .top-tiles strong { font-size: 1.35rem; } .top-tiles span, .metric-grid span { color: var(--color-text-2); font-size: 0.78rem; } .metric-grid strong { font-size: 1.25rem; }
  .tracking { font-size: 0.78rem; } .analytics-card, .providers { display: grid; gap: 1rem; padding: 1rem; border: 1px solid var(--color-border); border-radius: 0.65rem; } .section-heading, .chart-heading, .provider-heading { display: flex; justify-content: space-between; align-items: start; gap: 0.7rem; } .badge { border: 1px solid var(--color-border); border-radius: 9rem; padding: 0.2rem 0.55rem; color: var(--color-text-2); font-size: 0.73rem; white-space: nowrap; }
  .charts { display: grid; grid-template-columns: minmax(0, 1.3fr) minmax(15rem, 0.9fr); gap: 0.8rem; } .chart { display: grid; gap: 0.8rem; padding: 0.8rem; border: 1px solid var(--color-border); border-radius: 0.55rem; } .heatmap { display: grid; grid-template-columns: repeat(14, minmax(0, 1fr)); gap: 0.25rem; min-height: 4.2rem; align-content: center; } .heatmap span, .legend i { width: 100%; aspect-ratio: 1; border: 1px solid var(--color-border); border-radius: 0.2rem; background: var(--color-elevated); } .level-1 { background: color-mix(in srgb, var(--color-accent) 20%, var(--color-elevated)) !important; } .level-2 { background: color-mix(in srgb, var(--color-accent) 40%, var(--color-elevated)) !important; } .level-3 { background: color-mix(in srgb, var(--color-accent) 65%, var(--color-elevated)) !important; } .level-4 { background: var(--color-accent) !important; } .legend { display: flex; align-items: center; gap: 0.25rem; color: var(--color-text-2); font-size: 0.7rem; } .legend span:first-child { margin-right: auto; } .legend span:nth-last-child(1) { margin-left: auto; } .legend i { width: 0.7rem; flex: 0 0 auto; }
  .mix-bar, .provider-bar { display: flex; height: 0.55rem; overflow: hidden; border-radius: 9rem; background: var(--color-border); } .mix-bar i, .provider-bar i { display: block; min-width: 0; } .input { background: var(--color-accent); } .output { background: var(--color-good); } .cache { background: var(--color-attention); } .reasoning { background: var(--color-live); } .mix-legend { display: grid; gap: 0.35rem; color: var(--color-text-2); font-size: 0.73rem; } .mix-legend span { display: flex; align-items: center; gap: 0.35rem; } .dot { width: 0.55rem; height: 0.55rem; border-radius: 50%; }
  .provider-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(15rem, 1fr)); gap: 0.7rem; } .provider-grid article { display: grid; gap: 0.6rem; padding: 0.85rem; border: 1px solid var(--color-border); border-radius: 0.55rem; } .provider-heading span { color: var(--color-good); font-size: 0.75rem; } .provider-stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 0.5rem; } .provider-stats span { display: grid; gap: 0.15rem; font-size: 1rem; } .provider-stats small { font-size: 0.7rem; } .provider-bar i { background: var(--color-accent); }
  @media (max-width: 48rem) { .top-tiles, .metric-grid, .charts { grid-template-columns: 1fr 1fr; } .charts .chart:first-child { grid-column: 1 / -1; } } @media (max-width: 32rem) { .top-tiles, .metric-grid, .charts { grid-template-columns: 1fr; } }
</style>
