// The owner's neon 3D spinner set (TSK-1391). Each id names spinners/<id>.svg,
// generated by scripts/generateNeonSpinners.ts.
export const SPINNER_IDS = [
  'cube', 'octahedron', 'tetrahedron', 'icosahedron', 'star', 'gyroscope', 'dna', 'gyro-armillary',
  'gyro-cross', 'gyro-riders', 'gyro-precess', 'gyro-toy', 'gyro-linked', 'gyro-ripple', 'gyro-torus', 'gyro-cascade'
] as const;

export type SpinnerId = (typeof SPINNER_IDS)[number];

// A seed (a session's ownedId) always maps to the same design; no seed picks at random.
export function pickSpinner(seed?: string): SpinnerId {
  if (seed === undefined) return SPINNER_IDS[Math.floor(Math.random() * SPINNER_IDS.length)];
  let hash = 0;
  for (let index = 0; index < seed.length; index += 1) hash = (Math.imul(hash, 31) + seed.charCodeAt(index)) | 0;
  return SPINNER_IDS[(hash >>> 0) % SPINNER_IDS.length];
}
